use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "7c40ff83353d89452f86c4d413a09ed8b4d95f8dd578b53f3c1acf97ac079415"

search:
  formats:
    - html
    - json
  default_lang: "de"

engines:
  - name: google
    engine: google
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    disabled: false
  - name: brave
    engine: brave
    disabled: false
  - name: wikipedia
    engine: wikipedia
    disabled: false
